export type ICLRecordDefinition = {
  code: string;
  name: string;
  fields: Field[];
}

export type FieldDataType = "N" | "A" | "ANS" | "AN" | "B" | "NB" | "NBSM" | "NS" | "NBSMOS" | "Binary";

export type Field = {
  length: number | string;
  name: string;
  alias: string;
  type: FieldDataType;
  usage: string;
}

const fileHeaderRecord: ICLRecordDefinition = {
  code: "01",
  name: "File Header Record",
  fields: [{
    length: 2,
    name: "Record Type",
    alias: 'recordType',
    type: 'N',
    usage: 'M',
  },
  {
    length: 2,
    name: "Standard Level",
    alias: 'standardLevel',
    type: 'N',
    usage: 'M',
  },
  {
    length: 1,
    name: "Test File Indicator",
    alias: 'testFileIndicator',
    type: 'A',
    usage: 'M',
  },
  {
    length: 9,
    name: "Immediate Destination Routing Number",
    alias: 'immediateDestinationRoutingNumber',
    type: 'N',
    usage: 'M',
  },
  {
    length: 9,
    name: "Immediate Origin Routing Number",
    alias: 'immediateOriginRoutingNumber',
    type: 'N',
    usage: 'M',
  },
  {
    length: 8,
    name: "File Creation Date",
    alias: 'fileCreationDate',
    type: 'N',
    usage: 'M',
  },
  {
    length: 4,
    name: "File Creation Time",
    alias: 'fileCreationTime',
    type: 'N',
    usage: 'M',
  },
  {
    length: 1,
    name: "Resend Indicator",
    alias: 'resendIndicator',
    type: 'A',
    usage: 'M',
  },
  {
    length: 18,
    name: "Immediate Destination Name",
    alias: 'immediateDestinationName',
    type: 'ANS',
    usage: 'C',
  },
  {
    length: 18,
    name: "Immediate Origin Name",
    alias: 'immediateOriginName',
    type: 'ANS',
    usage: 'C',
  },
  {
    length: 1,
    name: "File ID Modifier",
    alias: 'fileIDModifier',
    type: 'AN',
    usage: 'C',
  },
  {
    length: 2,
    name: "Country Code",
    alias: 'countryCode',
    type: 'A',
    usage: 'C',
  },
  {
    length: 4,
    name: "User Field",
    alias: 'userField',
    type: 'ANS',
    usage: 'C',
  },
  {
    length: 1,
    name: "Companion Document Indicator",
    alias: 'companionDocumentIndicator',
    type: 'AN',
    usage: 'C',
  },
  ],
};

const cashLetterHeaderRecord: ICLRecordDefinition = {
  code: "10",
  name: "Cash Letter Header Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 2,
      name: "Collection Type Indicator",
      alias: "collectionTypeIndicator",
      type: "N",
      usage: "M",
    },
    {
      length: 9,
      name: "Destination Routing Number",
      alias: "destinationRoutingNumber",
      type: "N",
      usage: "M",
    },
    {
      length: 9,
      name: "ECE Institution Routing Number",
      alias: "eceInstitutionRoutingNumber",
      type: "N",
      usage: "M",
    },
    {
      length: 8,
      name: "Cash Letter Business Date",
      alias: "cashLetterBusinessDate",
      type: "N",
      usage: "M",
    },
    {
      length: 8,
      name: "Cash Letter Creation Date",
      alias: "cashLetterCreationDate",
      type: "N",
      usage: "M",
    },
    {
      length: 4,
      name: "Cash Letter Creation Time",
      alias: "cashLetterCreationTime",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Cash Letter Record Type Indicator",
      alias: "cashLetterRecordTypeIndicator",
      type: "A",
      usage: "M",
    },
    {
      length: 1,
      name: "Cash Letter Documentation Type Indicator",
      alias: "cashLetterDocumentationTypeIndicator",
      type: "AN",
      usage: "C",
    },
    {
      length: 8,
      name: "Cash Letter ID",
      alias: "cashLetterID",
      type: "AN",
      usage: "M",
    },
    {
      length: 14,
      name: "Originator Contact Name",
      alias: "originatorContactName",
      type: "ANS",
      usage: "C",
    },
    {
      length: 10,
      name: "Originator Contact Phone Number",
      alias: "originatorContactPhoneNumber",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Fed Work Type",
      alias: "fedWorkType",
      type: "AN",
      usage: "C",
    },
    {
      length: 1,
      name: "Returns Indicator",
      alias: "returnsIndicator",
      type: "A",
      usage: "M",
    },
    {
      length: 1,
      name: "User Field",
      alias: "userField",
      type: "ANS",
      usage: "C",
    },
    {
      length: 1,
      name: "Reserved",
      alias: "reserved",
      type: "B",
      usage: "M",
    },
  ],
};

const bundleHeaderRecord: ICLRecordDefinition = {
  code: "20",
  name: "Bundle Header Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 2,
      name: "Collection Type Indicator",
      alias: "collectionTypeIndicator",
      type: "N",
      usage: "M",
    },
    {
      length: 9,
      name: "Destination Routing Number",
      alias: "destinationRoutingNumber",
      type: "N",
      usage: "M",
    },
    {
      length: 9,
      name: "ECE Institution Routing Number",
      alias: "eceInstitutionRoutingNumber",
      type: "N",
      usage: "M",
    },
    {
      length: 8,
      name: "Bundle Business Date",
      alias: "bundleBusinessDate",
      type: "N",
      usage: "M",
    },
    {
      length: 8,
      name: "Bundle Creation Date",
      alias: "bundleCreationDate",
      type: "N",
      usage: "M",
    },
    {
      length: 10,
      name: "Bundle ID",
      alias: "bundleID",
      type: "AN",
      usage: "C",
    },
    {
      length: 4,
      name: "Bundle Sequence Number",
      alias: "bundleSequenceNumber",
      type: "NB",
      usage: "C",
    },
    {
      length: 2,
      name: "Cycle Number",
      alias: "cycleNumber",
      type: "AN",
      usage: "C",
    },
    {
      length: 9,
      name: "Reserved",
      alias: "reserved1",
      type: "B",
      usage: "M",
    },
    {
      length: 5,
      name: "User Field",
      alias: "userField",
      type: "ANS",
      usage: "C",
    },
    {
      length: 12,
      name: "Reserved",
      alias: "reserved2",
      type: "B",
      usage: "M",
    },
  ],
};

const checkDetailRecord: ICLRecordDefinition = {
  code: "25",
  name: "Check Detail Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 15,
      name: "Auxiliary On-Us",
      alias: "auxiliaryOnUs",
      type: "NBSM",
      usage: "C",
    },
    {
      length: 1,
      name: "External Processing Code",
      alias: "externalProcessingCode",
      type: "NS",
      usage: "C",
    },
    {
      length: 8,
      name: "Payor Bank Routing Number",
      alias: "payorBankRoutingNumber",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Payor Bank Routing Number Check Digit",
      alias: "payorBankRoutingNumberCheckDigit",
      type: "N",
      usage: "M",
    },
    {
      length: 20,
      name: "On-Us",
      alias: "onUs",
      type: "NBSMOS",
      usage: "C",
    },
    {
      length: 10,
      name: "Item Amount",
      alias: "itemAmount",
      type: "N",
      usage: "M",
    },
    {
      length: 15,
      name: "ECE Institution Item Sequence Number",
      alias: "eceInstitutionItemSequenceNumber",
      type: "NB",
      usage: "M",
    },
    {
      length: 1,
      name: "Documentation Type Indicator",
      alias: "documentationTypeIndicator",
      type: "AN",
      usage: "C",
    },
    {
      length: 1,
      name: "Return Acceptance Indicator",
      alias: "returnAcceptanceIndicator",
      type: "AN",
      usage: "C",
    },
    {
      length: 1,
      name: "MICR Valid Indicator",
      alias: "micrValidIndicator",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "BOFD Indicator",
      alias: "bofdIndicator",
      type: "A",
      usage: "M",
    },
    {
      length: 2,
      name: "Check Detail Record Addendum Count",
      alias: "checkDetailRecordAddendumCount",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Correction Indicator",
      alias: "correctionIndicator",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Archive Type Indicator",
      alias: "archiveTypeIndicator",
      type: "AN",
      usage: "C",
    },
  ],
};

const checkDetailAddendumARecord: ICLRecordDefinition = {
  code: "26",
  name: "Check Detail Addendum A Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Check Detail Addendum A Record Number",
      alias: "checkDetailAddendumARecordNumber",
      type: "N",
      usage: "M",
    },
    {
      length: 9,
      name: "Return Location Routing Number",
      alias: "returnLocationRoutingNumber",
      type: "N",
      usage: "M",
    },
    {
      length: 8,
      name: "BOFD / Endorsement Date",
      alias: "bofdEndorsementDate",
      type: "N",
      usage: "M",
    },
    {
      length: 15,
      name: "BOFD Item Sequence Number",
      alias: "bofdItemSequenceNumber",
      type: "NB",
      usage: "C",
    },
    {
      length: 18,
      name: "Deposit Account Number at BOFD",
      alias: "depositAccountNumberAtBOFD",
      type: "ANS",
      usage: "C",
    },
    {
      length: 5,
      name: "BOFD Deposit Branch",
      alias: "bofdDepositBranch",
      type: "ANS",
      usage: "C",
    },
    {
      length: 15,
      name: "Payee Name",
      alias: "payeeName",
      type: "ANS",
      usage: "C",
    },
    {
      length: 1,
      name: "Truncation Indicator",
      alias: "truncationIndicator",
      type: "A",
      usage: "M",
    },
    {
      length: 1,
      name: "BOFD Conversion Indicator",
      alias: "bofdConversionIndicator",
      type: "AN",
      usage: "C",
    },
    {
      length: 1,
      name: "BOFD Correction Indicator",
      alias: "bofdCorrectionIndicator",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "User Field",
      alias: "userField",
      type: "ANS",
      usage: "C",
    },
    {
      length: 3,
      name: "Reserved",
      alias: "reserved",
      type: "B",
      usage: "M",
    },
  ],
};

const checkDetailAddendumBRecord: ICLRecordDefinition = {
  code: "27",
  name: "Check Detail Addendum B Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Image Reference Key Indicator",
      alias: "imageReferenceKeyIndicator",
      type: "N",
      usage: "M",
    },
    {
      length: 15,
      name: "Microfilm Archive Sequence Number",
      alias: "microfilmArchiveSequenceNumber",
      type: "NB",
      usage: "C",
    },
    {
      length: 4,
      name: "Length of Image Reference Key",
      alias: "lengthOfImageReferenceKey",
      type: "N",
      usage: "M",
    },
    {
      length: "lengthOfImageReferenceKey",
      name: "Image Reference Key",
      alias: "imageReferenceKey",
      type: "ANS",
      usage: "C",
    },
    {
      length: 15,
      name: "Description",
      alias: "description",
      type: "ANS",
      usage: "C",
    },
    {
      length: 4,
      name: "User Field",
      alias: "userField",
      type: "ANS",
      usage: "C",
    },
    {
      length: 5,
      name: "Reserved",
      alias: "reserved",
      type: "B",
      usage: "M",
    },
  ],
};

const checkDetailAddendumCRecord: ICLRecordDefinition = {
  code: "28",
  name: "Check Detail Addendum C Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 2,
      name: "Check Detail Addendum C Record Number",
      alias: "checkDetailAddendumCRecordNumber",
      type: "N",
      usage: "M",
    },
    {
      length: 8,
      name: "Endorsing Bank Routing Number",
      alias: "endorsingBankRoutingNumber",
      type: "N",
      usage: "M",
    },
    {
      length: 9,
      name: "BOFD / Endorsement Business Date",
      alias: "bofdEndorsementBusinessDate",
      type: "N",
      usage: "M",
    },
    {
      length: 15,
      name: "Endorsing Bank Item Sequence Number",
      alias: "endorsingBankItemSequenceNumber",
      type: "NB",
      usage: "C",
    },
    {
      length: 1,
      name: "Truncation Indicator",
      alias: "truncationIndicator",
      type: "A",
      usage: "C",
    },
    {
      length: 1,
      name: "Endorsing Bank Conversion Indicator",
      alias: "endorsingBankConversionIndicator",
      type: "AN",
      usage: "C",
    },
    {
      length: 1,
      name: "Endorsing Bank Correction Indicator",
      alias: "endorsingBankCorrectionIndicator",
      type: "A",
      usage: "C",
    },
    {
      length: 1,
      name: "Return Reason",
      alias: "returnReason",
      type: "AN",
      usage: "C",
    },
    {
      length: 19,
      name: "User Field",
      alias: "userField",
      type: "ANS",
      usage: "C",
    },
    {
      length: 1,
      name: "Endorsing Bank Identifier",
      alias: "endorsingBankIdentifier",
      type: "AN",
      usage: "C",
    },
    {
      length: 20,
      name: "Reserved",
      alias: "reserved",
      type: "B",
      usage: "M",
    },
  ],
};

const returnDetailRecord: ICLRecordDefinition = {
  code: "31",
  name: "Return Detail Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 8,
      name: "Payor Bank Routing Number",
      alias: "payorBankRoutingNumber",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Payor Bank Routing Number Check Digit",
      alias: "payorBankRoutingNumberCheckDigit",
      type: "N",
      usage: "M",
    },
    {
      length: 20,
      name: "On-Us",
      alias: "onUs",
      type: "NBSMOS",
      usage: "C",
    },
    {
      length: 10,
      name: "Item Amount",
      alias: "itemAmount",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Return Reason",
      alias: "returnReason",
      type: "AN",
      usage: "M",
    },
    {
      length: 2,
      name: "Return Record Addendum Count",
      alias: "returnRecordAddendumCount",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Return Documentation Type Indicator",
      alias: "returnDocumentationTypeIndicator",
      type: "AN",
      usage: "C",
    },
    {
      length: 8,
      name: "Forward Bundle Date",
      alias: "forwardBundleDate",
      type: "N",
      usage: "C",
    },
    {
      length: 15,
      name: "ECE Institution Item Sequence Number",
      alias: "eceInstitutionItemSequenceNumber",
      type: "NB",
      usage: "C",
    },
    {
      length: 1,
      name: "External Processing Code",
      alias: "externalProcessingCode",
      type: "NS",
      usage: "C",
    },
    {
      length: 1,
      name: "Return Notification Indicator",
      alias: "returnNotificationIndicator",
      type: "N",
      usage: "M",
    },
    {
      length: 2,
      name: "Archive Type Indicator",
      alias: "archiveTypeIndicator",
      type: "AN",
      usage: "M",
    },
    {
      length: 1,
      name: "Number of Times Returned",
      alias: "numberOfTimesReturned",
      type: "N",
      usage: "C",
    },
    {
      length: 8,
      name: "Reserved",
      alias: "reserved",
      type: "B",
      usage: "M",
    },
  ],
};

const returnDetailAddendumARecord: ICLRecordDefinition = {
  code: "32",
  name: "Return Detail Addendum A Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Return Detail Addendum A Record Number",
      alias: "returnDetailAddendumARecordNumber",
      type: "N",
      usage: "M",
    },
    {
      length: 9,
      name: "Return Location Routing Number",
      alias: "returnLocationRoutingNumber",
      type: "N",
      usage: "M",
    },
    {
      length: 8,
      name: "BOFD / Endorsement Date",
      alias: "bofdEndorsementDate",
      type: "N",
      usage: "M",
    },
    {
      length: 15,
      name: "BOFD Item Sequence Number",
      alias: "bofdItemSequenceNumber",
      type: "NB",
      usage: "C",
    },
    {
      length: 18,
      name: "Deposit Account Number at BOFD",
      alias: "depositAccountNumberAtBOFD",
      type: "ANS",
      usage: "C",
    },
    {
      length: 5,
      name: "BOFD Deposit Branch",
      alias: "bofdDepositBranch",
      type: "ANS",
      usage: "C",
    },
    {
      length: 15,
      name: "Payee Name",
      alias: "payeeName",
      type: "ANS",
      usage: "C",
    },
    {
      length: 1,
      name: "Truncation Indicator",
      alias: "truncationIndicator",
      type: "A",
      usage: "M",
    },
    {
      length: 1,
      name: "BOFD Conversion Indicator",
      alias: "bofdConversionIndicator",
      type: "AN",
      usage: "C",
    },
    {
      length: 1,
      name: "BOFD Correction Indicator",
      alias: "bofdCorrectionIndicator",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "User Field",
      alias: "userField",
      type: "ANS",
      usage: "C",
    },
    {
      length: 3,
      name: "Reserved",
      alias: "reserved",
      type: "B",
      usage: "M",
    },
  ],
};

const returnDetailAddendumBRecord: ICLRecordDefinition = {
  code: "33",
  name: "Return Detail Addendum B Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 18,
      name: "Payor Bank Name",
      alias: "payorBankName",
      type: "N",
      usage: "C",
    },
    {
      length: 15,
      name: "Auxiliary On-Us",
      alias: "auxiliaryOnUs",
      type: "NBSM",
      usage: "C",
    },
    {
      length: 15,
      name: "Payor Bank Item Sequence Number",
      alias: "payorBankItemSequenceNumber",
      type: "NB",
      usage: "C",
    },
    {
      length: 8,
      name: "Payor Bank Business Date",
      alias: "payorBankBusinessDate",
      type: "N",
      usage: "C",
    },
    {
      length: 15,
      name: "Payor Account Name",
      alias: "payorAccountName",
      type: "ANS",
      usage: "C",
    },
  ],
};

const returnDetailAddendumCRecord: ICLRecordDefinition = {
  code: "34",
  name: "Return Detail Addendum C Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Image Reference Key Indicator",
      alias: "imageReferenceKeyIndicator",
      type: "N",
      usage: "M",
    },
    {
      length: 15,
      name: "Microfilm Archive Sequence Number",
      alias: "microfilmArchiveSequenceNumber",
      type: "NB",
      usage: "C",
    },
    {
      length: 4,
      name: "Length of Image Reference Key",
      alias: "lengthOfImageReferenceKey",
      type: "N",
      usage: "M",
    },
    {
      length: "lengthOfImageReferenceKey",
      name: "Image Reference Key",
      alias: "imageReferenceKey",
      type: "ANS",
      usage: "C",
    },
    {
      length: 15,
      name: "Description",
      alias: "description",
      type: "ANS",
      usage: "C",
    },
    {
      length: 4,
      name: "User Field",
      alias: "userField",
      type: "ANS",
      usage: "C",
    },
    {
      length: 5,
      name: "Reserved",
      alias: "reserved",
      type: "B",
      usage: "M",
    },
  ],
};

const returnDetailAddendumDRecord: ICLRecordDefinition = {
  code: "35",
  name: "Return Detail Addendum D Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Return Detail Addendum D Record Number",
      alias: "returnDetailAddendumDRecordNumber",
      type: "N",
      usage: "M",
    },
    {
      length: 9,
      name: "Endorsing Bank Routing Number",
      alias: "endorsingBankRoutingNumber",
      type: "N",
      usage: "M",
    },
    {
      length: 8,
      name: "BOFD / Endorsement Date",
      alias: "bofdEndorsementDate",
      type: "N",
      usage: "M",
    },
    {
      length: 15,
      name: "Endorsing Bank Sequence Number",
      alias: "endorsingBankSequenceNumber",
      type: "NB",
      usage: "M",
    },
    {
      length: 1,
      name: "Truncation Indicator",
      alias: "truncationIndicator",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Endorsing Bank Conversion Indicator",
      alias: "endorsingBankConversionIndicator",
      type: "AN",
      usage: "C",
    },
    {
      length: 1,
      name: "Endorsing Bank Correction Indicator",
      alias: "endorsingBankCorrectionIndicator",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Return Reason",
      alias: "returnReason",
      type: "AN",
      usage: "C",
    },
    {
      length: 1,
      name: "User Field",
      alias: "userField",
      type: "ANS",
      usage: "C",
    },
    {
      length: 1,
      name: "Endorsing Bank Identifier",
      alias: "endorsingBankIdentifier",
      type: "N",
      usage: "C",
    },
    {
      length: 20,
      name: "Reserved",
      alias: "reserved",
      type: "B",
      usage: "M",
    },
  ],
};

const imageViewDetailRecord: ICLRecordDefinition = {
  code: "50",
  name: "Image View Detail Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Image Indicator",
      alias: "imageIndicator",
      type: "N",
      usage: "M",
    },
    {
      length: 9,
      name: "Image Creator Routing Number",
      alias: "imageCreatorRoutingNumber",
      type: "N",
      usage: "M",
    },
    {
      length: 8,
      name: "Image Creator Date",
      alias: "imageCreatorDate",
      type: "N",
      usage: "M",
    },
    {
      length: 2,
      name: "Image View Format Indicator",
      alias: "imageViewFormatIndicator",
      type: "N",
      usage: "C",
    },
    {
      length: 2,
      name: "Image View Compression Algorithm Identifier",
      alias: "imageViewCompressionAlgorithmIdentifier",
      type: "N",
      usage: "C",
    },
    {
      length: 7,
      name: "Image View Data Size",
      alias: "imageViewDataSize",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "View Side Indicator",
      alias: "viewSideIndicator",
      type: "N",
      usage: "M",
    },
    {
      length: 2,
      name: "View Descriptor",
      alias: "viewDescriptor",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Digital Signature Indicator",
      alias: "digitalSignatureIndicator",
      type: "N",
      usage: "C",
    },
    {
      length: 2,
      name: "Digital Signature Method",
      alias: "digitalSignatureMethod",
      type: "N",
      usage: "C",
    },
    {
      length: 5,
      name: "Security Key Size",
      alias: "securityKeySize",
      type: "N",
      usage: "C",
    },
    {
      length: 7,
      name: "Start of Protected Data",
      alias: "startOfProtectedData",
      type: "N",
      usage: "C",
    },
    {
      length: 7,
      name: "Length of Protected Data",
      alias: "lengthOfProtectedData",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Image Recreate Indicator",
      alias: "imageRecreateIndicator",
      type: "N",
      usage: "C",
    },
    {
      length: 8,
      name: "User Field",
      alias: "userField",
      type: "ANS",
      usage: "C",
    },
    {
      length: 1,
      name: "Reserved",
      alias: "reserved1",
      type: "B",
      usage: "M",
    },
    {
      length: 1,
      name: "Override Indicator",
      alias: "overrideIndicator",
      type: "AN",
      usage: "C",
    },
    {
      length: 13,
      name: "Reserved",
      alias: "reserved2",
      type: "B",
      usage: "M",
    },
  ],
};

const imageViewDataRecord: ICLRecordDefinition = {
  code: "52",
  name: "Image View Data Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 9,
      name: "ECE Institution Routing Number",
      alias: "eceInstitutionRoutingNumber",
      type: "N",
      usage: "M",
    },
    {
      length: 8,
      name: "Bundle Business Date",
      alias: "bundleBusinessDate",
      type: "N",
      usage: "M",
    },
    {
      length: 2,
      name: "Cycle Number",
      alias: "cycleNumber",
      type: "AN",
      usage: "C",
    },
    {
      length: 15,
      name: "ECE Institution Item Sequence Number",
      alias: "eceInstitutionItemSequenceNumber",
      type: "NB",
      usage: "C",
    },
    {
      length: 16,
      name: "Security Originator Name",
      alias: "securityOriginatorName",
      type: "ANS",
      usage: "C",
    },
    {
      length: 16,
      name: "Security Authenticator Name",
      alias: "securityAuthenticatorName",
      type: "ANS",
      usage: "C",
    },
    {
      length: 16,
      name: "Security Key Name",
      alias: "securityKeyName",
      type: "ANS",
      usage: "C",
    },
    {
      length: 1,
      name: "Clipping Origin",
      alias: "clippingOrigin",
      type: "NB",
      usage: "C",
    },
    {
      length: 4,
      name: "Clipping Coordinate h1",
      alias: "clippingCoordinateH1",
      type: "N",
      usage: "C",
    },
    {
      length: 4,
      name: "Clipping Coordinate h2",
      alias: "clippingCoordinateH2",
      type: "N",
      usage: "C",
    },
    {
      length: 4,
      name: "Clipping Coordinate v1",
      alias: "clippingCoordinateV1",
      type: "N",
      usage: "C",
    },
    {
      length: 4,
      name: "Clipping Coordinate v2",
      alias: "clippingCoordinateV2",
      type: "N",
      usage: "C",
    },
    {
      length: 4,
      name: "Length of Image Reference Key",
      alias: "lengthOfImageReferenceKey",
      type: "NB",
      usage: "C",
    },
    {
      length: "lengthOfImageReferenceKey",
      name: "Image Reference Key",
      alias: "imageReferenceKey",
      type: "ANS",
      usage: "C",
    },
    {
      length: 5,
      name: "Length of Digital Signature",
      alias: "lengthOfDigitalSignature",
      type: "NB",
      usage: "C",
    },
    {
      length: "lengthOfDigitalSignature",
      name: "Digital Signature",
      alias: "digitalSignature",
      type: "Binary",
      usage: "C",
    },
    {
      length: 7,
      name: "Length of Image Data",
      alias: "lengthOfImageData",
      type: "NB",
      usage: "C",
    },
    {
      length: "lengthOfImageData",
      name: "Image Data",
      alias: "imageData",
      type: "Binary",
      usage: "C",
    },
  ],
};

const imageViewAnalysisRecord: ICLRecordDefinition = {
  code: "54",
  name: "Image View Analysis Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Global Image Quality",
      alias: "globalImageQuality",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Global Image Usability",
      alias: "globalImageUsability",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Imaging Bank Specific Test",
      alias: "imagingBankSpecificTest",
      type: "N",
      usage: "M",
    },
    {
      length: 1,
      name: "Partial Image",
      alias: "partialImage",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Excessive Image Skew",
      alias: "excessiveImageSkew",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Piggyback Image",
      alias: "piggybackImage",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Too Light Or Too Dark",
      alias: "tooLightOrTooDark",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Streaks And Or Bands",
      alias: "streaksAndOrBands",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Below Minimum Image Size",
      alias: "belowMinimumImageSize",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Exceeds Maximum Image Size",
      alias: "exceedsMaximumImageSize",
      type: "N",
      usage: "C",
    },
    {
      length: 13,
      name: "Reserved",
      alias: "reserved1",
      type: "B",
      usage: "M",
    },
    {
      length: 1,
      name: "Image-Enabled POD",
      alias: "imageEnabledPOD",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Source Document Bad",
      alias: "sourceDocumentBad",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Date Usability",
      alias: "dateUsability",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Payee Usability",
      alias: "payeeUsability",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Convenience Amount Usability",
      alias: "convenienceAmountUsability",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Amount in Words (Legal Amount) Usability",
      alias: "amountInWordsUsability",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Signature Usability",
      alias: "signatureUsability",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Payor Name And Address Usability",
      alias: "payorNameAndAddressUsability",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "MICR Line Usability",
      alias: "micrLineUsability",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Memo Line Usability",
      alias: "memoLineUsability",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Payor Bank Name And Address Usability",
      alias: "payorBankNameAndAddressUsability",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Payee Endorsement Usability",
      alias: "payeeEndorsementUsability",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Bank Of First Deposit Endorsement Usability",
      alias: "bankOfFirstDepositEndorsementUsability",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Transit Endorsement Usability",
      alias: "transitEndorsementUsability",
      type: "N",
      usage: "C",
    },
    {
      length: 6,
      name: "Reserved",
      alias: "reserved2",
      type: "B",
      usage: "M",
    },
    {
      length: 20,
      name: "User Field",
      alias: "userField",
      type: "ANS",
      usage: "C",
    },
    {
      length: 15,
      name: "Reserved",
      alias: "reserved3",
      type: "B",
      usage: "M",
    },
  ],
};

const bundleControlRecord: ICLRecordDefinition = {
  code: "70",
  name: "Bundle Control Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 4,
      name: "Items Within Bundle Count",
      alias: "itemsWithinBundleCount",
      type: "N",
      usage: "M",
    },
    {
      length: 12,
      name: "Bundle Total Amount",
      alias: "bundleTotalAmount",
      type: "N",
      usage: "M",
    },
    {
      length: 12,
      name: "MICR Valid Total Amount",
      alias: "micrValidTotalAmount",
      type: "N",
      usage: "C",
    },
    {
      length: 5,
      name: "Images within Bundle Count",
      alias: "imagesWithinBundleCount",
      type: "N",
      usage: "M",
    },
    {
      length: 20,
      name: "User Field",
      alias: "userField",
      type: "ANS",
      usage: "C",
    },
    {
      length: 1,
      name: "Bundle ID",
      alias: "bundleID",
      type: "N",
      usage: "C",
    },
    {
      length: 24,
      name: "Bundle Sequence Number",
      alias: "bundleSequenceNumber",
      type: "B",
      usage: "M",
    },
  ],
};

const routingNumberSummary: ICLRecordDefinition = {
  code: "85",
  name: "Routing Number Summary",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 9,
      name: "Routing Number Within Cash Letter",
      alias: "routingNumberWithinCashLetter",
      type: "N",
      usage: "M",
    },
    {
      length: 14,
      name: "Routing Number Total Amount",
      alias: "routingNumberTotalAmount",
      type: "N",
      usage: "M",
    },
    {
      length: 12,
      name: "Routing Number Item Count",
      alias: "routingNumberItemCount",
      type: "N",
      usage: "M",
    },
    {
      length: 24,
      name: "User Field",
      alias: "userField",
      type: "ANS",
      usage: "C",
    },
    {
      length: 25,
      name: "Reserved",
      alias: "reserved",
      type: "B",
      usage: "M",
    },
  ],
};

const cashLetterControlRecord: ICLRecordDefinition = {
  code: "90",
  name: "Cash Letter Control Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 6,
      name: "Bundle Count",
      alias: "bundleCount",
      type: "N",
      usage: "M",
    },
    {
      length: 8,
      name: "Items Within Cash Letter Count",
      alias: "itemsWithinCashLetterCount",
      type: "N",
      usage: "M",
    },
    {
      length: 14,
      name: "Cash Letter Total Amount",
      alias: "cashLetterTotalAmount",
      type: "N",
      usage: "M",
    },
    {
      length: 9,
      name: "Images Within Cash Letter Count",
      alias: "imagesWithinCashLetterCount",
      type: "N",
      usage: "M",
    },
    {
      length: 18,
      name: "ECE Institution Name",
      alias: "eceInstitutionName",
      type: "ANS",
      usage: "C",
    },
    {
      length: 8,
      name: "Settlement Date",
      alias: "settlementDate",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Credit Total Indicator",
      alias: "creditTotalIndicator",
      type: "N",
      usage: "C",
    },
    {
      length: 14,
      name: "Reserved",
      alias: "reserved",
      type: "B",
      usage: "M",
    },
  ],
};

const fileControlRecord: ICLRecordDefinition = {
  code: "99",
  name: "File Control Record",
  fields: [
    {
      length: 2,
      name: "Record Type",
      alias: "recordType",
      type: "N",
      usage: "M",
    },
    {
      length: 6,
      name: "Cash Letter Count",
      alias: "cashLetterCount",
      type: "N",
      usage: "M",
    },
    {
      length: 8,
      name: "Total Record Count",
      alias: "totalRecordCount",
      type: "N",
      usage: "M",
    },
    {
      length: 8,
      name: "Total Item Count",
      alias: "totalItemCount",
      type: "N",
      usage: "M",
    },
    {
      length: 16,
      name: "File Total Amount",
      alias: "fileTotalAmount",
      type: "N",
      usage: "M",
    },
    {
      length: 14,
      name: "Immediate Origin Contact Name",
      alias: "immediateOriginContactName",
      type: "ANS",
      usage: "C",
    },
    {
      length: 10,
      name: "Immediate Origin Contact Phone Number",
      alias: "immediateOriginContactPhoneNumber",
      type: "N",
      usage: "C",
    },
    {
      length: 1,
      name: "Credit Total Indicator",
      alias: "creditTotalIndicator",
      type: "N",
      usage: "C",
    },
    {
      length: 15,
      name: "Reserved",
      alias: "reserved",
      type: "B",
      usage: "M",
    },
  ],
};


const definitions = [
  fileHeaderRecord,
  cashLetterHeaderRecord,
  bundleHeaderRecord,
  checkDetailRecord,
  checkDetailAddendumARecord,
  checkDetailAddendumBRecord,
  checkDetailAddendumCRecord,
  returnDetailRecord,
  returnDetailAddendumARecord,
  returnDetailAddendumBRecord,
  returnDetailAddendumCRecord,
  returnDetailAddendumDRecord,
  imageViewDetailRecord,
  imageViewDataRecord,
  imageViewAnalysisRecord,
  bundleControlRecord,
  routingNumberSummary,
  cashLetterControlRecord,
  fileControlRecord,
];

export const iclRecordDefinitions = definitions.reduce((acc, definition) => {
  acc[definition.code] = definition;
  return acc;
}, {} as Record<string, ICLRecordDefinition>);
